from setuptools import setup

setup(
    name="zerochain",
    version="0.0.1-beta",
    description="Python SDK for use on the ZeroChain network, allowing developers to leverage full power of the Zerochain network with Python",
    url="https://github.com/subaquatic-pierre/zerochain-sdk-py",
    author="Pierre du Toit",
    author_email="subaquatic-pierre@gmail.com",
    license="BSD 2-clause",
    packages=["zerochain"],
    install_requires=[
        "appdirs==1.4.4",
        "attrs==21.2.0",
        "black==21.7b0",
        "certifi==2021.5.30",
        "charset-normalizer==2.0.3",
        "click==8.0.1",
        "idna==3.2",
        "iniconfig==1.1.1",
        "mypy-extensions==0.4.3",
        "packaging==21.0",
        "pathspec==0.9.0",
        "pluggy==0.13.1",
        "py==1.10.0",
        "pyparsing==2.4.7",
        "pytest==6.2.4",
        "PyYAML==5.4.1",
        "reedsolo==1.5.4",
        "regex==2021.7.6",
        "requests==2.26.0",
        "requests-toolbelt==0.9.1",
        "toml==0.10.2",
        "tomli==1.2.0",
        "urllib3==1.26.6",
    ],
    classifiers=[
        "Development Status :: 1 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python",
        "Topic :: Blockchain :: SDK",
    ],
)
